### ISSUE TITLE
Crashes under 2018a

### ISSUE THREAD

**Issue by DavidBrainard** [justingardner/mgl#29]
When we try to use mgl under Matlab 2018a, we get a crash inside of mglPrivateOpen, if
we try to use a fullscreen window.  Seems to work inside a non-fullscreen window.

We will try to look further when we get a chance. If anyone knows the problem/fix, though,
we are interested.

**Comment by justingardner** [comment]
Thanks, David, for letting us know. I haven't been upgrading Matlab for a while now as it seems that Mathworks is intent on just making life worse with every release, but will try to track this down when I get a chance. 

Unrelated - but have you run into issues with setting the gamma table in MacOS High Sierra? There seems to be some table interpolation going on that I haven't figured out how to circumvent. This shows up, for example, if you reserve a few entries for a specific color, like say, setting the first table item to red and then having all the rest of the table set for grayscale (something we typically due to show low contrast stimuli). The red bleeds into the grayscale items. This had been a problem in previous MacOS versions which seemed to have to do with their switch to using a 1024 entry gamma table when supported on the display card, by interpolating a 256 entry table, which I had fixed by setting directly a 1024 entry table. However that fix no longer seems to work and I haven't found a good work around. Any thoughts?

**Comment by justingardner** [comment]
Closing out - we are working on a new version of metal (based on metal) with new compilation scripts mglMakeMetal this will be the new default version of mgl for newer systems / matlab versions / OS versions
